name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-10.15
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.2,name=iPad (7th generation)']
        xcode: ['/Applications/Xcode_12.2.app/Contents/Developer']  
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        
      - name: Install and run xcodegen
        run: |
          brew install xcodegen
          xcodegen generate

      - name: Fastlane setup
        run: |
          fastlane setup_keychain --verbose

      - name: Build
        env:
          destination: ${{ matrix.destination }}
          DEVELOPER_DIR: ${{ matrix.xcode }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          API_KEY_JSON: ${{ secrets.API_KEY_JSON }}
        run: |
          fastlane build --verbose