name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-10.15
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.2,name=iPad (7th generation)']
        xcode: ['/Applications/Xcode_12.2.app/Contents/Developer']  
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        
      - name: Install and run xcodegen
        run: |
          brew install xcodegen
          xcodegen generate

      - name: Fastlane setup
        run: |
          fastlane setup_keychain --verbose

      - name: Build
        env:
          destination: ${{ matrix.destination }}
          DEVELOPER_DIR: ${{ matrix.xcode }}
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_PAT: ${{ secrets.MATCH_PAT }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        run: |
          fastlane build --verbose